INCLUDEPATH += $$PWD/src
LIBRARYPATH += $$PWD/lib
QMAKE_RPATHDIR = $$OUT_PWD/lib

QT += opengl

QMAKE_INCDIR += $$INCLUDEPATH
QMAKE_LIBDIR += $$LIBRARYPATH
LIBS += -L$$QMAKE_LIBDIR -L. -lscenegraph

win32:DEFINES += Q_SCENEGRAPH_EXPORT=__declspec(dllimport)
unix:DEFINES += Q_SCENEGRAPH_EXPORT=""
